# Generated by Django 5.0.1 on 2024-01-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_review_name_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='amir', max_length=255),
            preserve_default=False,
        ),
    ]
